---
- name: Install Docker Suite
  hosts: localhost

  vars:
    docker_compose_version: "2.37.2"
    docker_config: "{{ lookup('env', 'HOME') }}/.docker"

  tasks:
    - name: Uninstall Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - docker-ce-rootless-extras
        state: absent
      become: true

    - name: Install Docker Engine via convenient script
      ansible.builtin.shell:
        cmd: curl -fsSL https://get.docker.com -o /tmp/get-docker.sh && sh /tmp/get-docker.sh
      become: true

    - name: Creates Docker Plugin Directory
      ansible.builtin.shell:
        cmd: mkdir -p "{{ docker_config }}/cli-plugins"

    - name: Install Docker Compose v{{ docker_compose_version }}
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-linux-x86_64"
        dest: "{{ docker_config }}/cli-plugins/docker-compose"
        mode: 0744 # user executable permission
        force: true
