---
- name: Install Poetry
  hosts: localhost
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install dependencies via apt
      ansible.builtin.apt:
        name: curl
        install_recommends: no

    - name: Install Poetry in /opt/poetry
      ansible.builtin.shell:
        cmd: curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python3 -

    - name: Create symlink in /usr/local/bin/poetry
      ansible.builtin.shell:
        cmd: ln --symbolic --force /opt/poetry/bin/poetry /usr/local/bin/poetry

    - name: Enable in-project virtualenvs creation
      ansible.builtin.shell:
        cmd: poetry config virtualenvs.in-project true
