---
- name: Restore configuration
  hosts: localhost

  tasks:
    - name: Restore decrypted password database
      ansible.builtin.copy:
        src: ../../config/passdb.kdbx
        dest: ~/passdb.kdbx
        mode: 0600
        decrypt: true
