---
- name: Restore configuration
  hosts: localhost

  tasks:
    - name: Restore decrypted SSH private key
      ansible.builtin.copy:
        src: ../../config/id_rsa
        dest: ~/.ssh/
        mode: 0600
        decrypt: true

    - name: Restore decrypted SSH public key
      ansible.builtin.copy:
        src: ../../config/id_rsa.pub
        dest: ~/.ssh/
        mode: 0600
        decrypt: true
