---
- name: Install UV
  hosts: localhost

  tasks:
    - name: Update apt cache and ensure cURL in the system
      ansible.builtin.apt:
        update_cache: yes
        name: curl
        install_recommends: no
      become: true

    - name: Install UV
      ansible.builtin.shell:
        cmd: curl -LsSf https://astral.sh/uv/install.sh | sh
